export const ERROR_CODES = {
  GENERIC: {
    INVALID_ARGUMENT: 'GENERIC.INVALID_ARGUMENT',
    OUT_OF_RANGE: 'GENERIC.OUT_OF_RANGE',
    NOT_PROVIDED: 'GENERIC.NOT_PROVIDED',
    CONFLICT: 'GENERIC.CONFLICT',
    NOT_FOUND: 'GENERIC.NOT_FOUND',
    INTERNAL_SERVER_ERROR: 'GENERIC.INTERNAL_SERVER_ERROR',
  },

  // User service
  USER: {
    NOT_FOUND: 'USER.NOT_FOUND',
    ALREADY_EXISTS: 'USER.ALREADY_EXISTS',
  },

  // Auth service
  AUTH: {
    EMAIL_ALREADY_REGISTERED: 'AUTH.EMAIL_ALREADY_REGISTERED',
    INVALID_CREDENTIALS: 'AUTH.INVALID_CREDENTIALS',
    UNAUTHORIZED: 'AUTH.UNAUTHORIZED',
  },

  // Payment service
  PAYMENT: {
    DECLINED: 'PAYMENT.DECLINED',
    INSUFFICIENT_FUNDS: 'PAYMENT.INSUFFICIENT_FUNDS',
  },
} as const;
